### ISSUE TITLE
Suggest Docker on Mac (beta)

### ISSUE THREAD

**Issue by orsenthil** [alexellis/HandsOnDocker#3]
https://github.com/alexellis/HandsOnDocker/blob/master/Labs.md#youre-on-a-mac suggests the old docker toolbox mechanism. I tried the tutorial with Docker on Mac, and it was quite smooth.

**Comment by alexellis** [comment]
Fair point - the beta was made public this week, so makes sense to include a word or two mentioning it. In my experience it should work just as well. `docker-machine ip` would be `localhost` instead.

**Comment by alexellis** [comment]
@orsenthil  https://github.com/alexellis/HandsOnDocker/pull/4
