### ISSUE TITLE
Dockerfile for Lab 12

### ISSUE THREAD

**Issue by shuntera** [alexellis/HandsOnDocker#9]
For Lab 12 I see this:

1. Build the image_upload image

But nothing under that shows what the Dockerfile consists of.

**Comment by alexellis** [comment]
> Build the image_upload image from the image_upload folder.

The image_upload folder is part of the labs code you cloned in an earlier step in the `Dockerfiles` folder.

**Comment by alexellis** [comment]
Thanks for the feedback, I've updated the instructions. How did you find the rest of the labs?
